# To use the default value, just comment out the property with a hashtag (#).

[settings]
# Path to download/save libs to. Paths can be absolute
# or relative. Relative paths are relative to the
# current working directory.
# Lets say that we want to download eagle libraries on Linux,
# output_path would look something like this:
# "/home/<your-username>/EAGLE/libraries"
output_path = "download"

# Path to watch for zipped .epw files.
# This is usually your downloads folder.
# Uncommenting this will enable watch-mode.
# watch_path = ""

# What format should be saved?
# eagle, kikad, ..
# Run with --help to see a list of available values.
# format = ""

# Component Search Engine Credentials
# Don't want to store credentials here?
# Comment out everything under this line.
[profile]
username = "" # This is usually your email you used to register with.
password = ""
